/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.controlsalidas;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;
import org.hibernate.Session;

/**
 *
 * @author Keloc
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    private viewPanel vistaSalidas = new viewPanel();
    private addPanel vistaAdd;
    private String usuarioActual;
    private String delPass;
    private String adminPass;
    private editorPanel editor;
    private ArrayList<String> loginAdds = new ArrayList();
    private Image arrow = getImg("return-arrow-f").getImage();
    private Image l1 = getImg("logo1").getImage();
    private Image l2 = getImg("logo2").getImage();
    private static JPanel login;
    private static JLabel reg;
    private static JPanel cp;
    
    public gui() {
        initComponents();
        connect();
        setPass();
        editor = new editorPanel(adminPass, delPass);
        loginAdds.add("DELEGADO");
        loginAdds.add("ADMIN");
        initDefs(usuario, loginAdds);
        volver.setIcon(resizeImage(arrow, volver));
        logo1L.setIcon(resizeImage(l1, logo1L));
        logo2L.setIcon(resizeImage(l2, logo2L));
        cambiarContent(loginPanel);
        volver.setVisible(false);
        login = loginPanel;
        reg = volver;
        cp = content;
    }

    public static JPanel getLogin() {
        return login;
    }

    public static JLabel getReg() {
        return reg;
    }

    public static JPanel getCp() {
        return cp;
    }
    
    public void setPass(){
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.beginTransaction();
            List<Pass> contras = session.createQuery("From Pass", Pass.class).list();
            adminPass = contras.get(0).getPassword();
            delPass = contras.get(1).getPassword();
            session.getTransaction().commit();
            session.close();
        } catch (Exception e) {
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
            e.printStackTrace();
        } finally {
            session.close();
        }
    }

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usuario = new javax.swing.JComboBox<>();
        loginBtn = new javax.swing.JButton();
        contrasPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contraF = new javax.swing.JPasswordField();
        mostrarC = new javax.swing.JToggleButton();
        dbConfigP = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        urlTF = new javax.swing.JTextField();
        usuarioTF = new javax.swing.JTextField();
        dbContra = new javax.swing.JPasswordField();
        dbContraT = new javax.swing.JToggleButton();
        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        volver = new javax.swing.JLabel();
        logosP = new javax.swing.JPanel();
        logo1L = new javax.swing.JLabel();
        logo2L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setMinimumSize(new java.awt.Dimension(810, 588));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sistema de Control de Salidas");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Usuario:");

        usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DELEGADO", "ADMIN" }));

        loginBtn.setText("ACCEDER");
        loginBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(usuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)))
                .addGap(153, 153, 153))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jLabel2.setText("Contraseña:");

        mostrarC.setText("Mostrar");
        mostrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contrasPanelLayout = new javax.swing.GroupLayout(contrasPanel);
        contrasPanel.setLayout(contrasPanelLayout);
        contrasPanelLayout.setHorizontalGroup(
            contrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contrasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contrasPanelLayout.createSequentialGroup()
                        .addComponent(contraF, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        contrasPanelLayout.setVerticalGroup(
            contrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contrasPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarC))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel14.setText("URL:");

        jLabel15.setText("USUARIO:");

        jLabel16.setText("CONTRASEÑA:");

        dbContraT.setText("Mostrar");
        dbContraT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbContraTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dbConfigPLayout = new javax.swing.GroupLayout(dbConfigP);
        dbConfigP.setLayout(dbConfigPLayout);
        dbConfigPLayout.setHorizontalGroup(
            dbConfigPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbConfigPLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(dbConfigPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dbContraT)
                    .addGroup(dbConfigPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(dbConfigPLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(18, 18, 18)
                            .addComponent(dbContra))
                        .addGroup(dbConfigPLayout.createSequentialGroup()
                            .addGroup(dbConfigPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addGap(45, 45, 45)
                            .addGroup(dbConfigPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(urlTF)
                                .addComponent(usuarioTF, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        dbConfigPLayout.setVerticalGroup(
            dbConfigPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbConfigPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dbConfigPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(urlTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dbConfigPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(usuarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dbConfigPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(dbContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbContraT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("frame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setMinimumSize(new java.awt.Dimension(810, 560));
        content.setPreferredSize(new java.awt.Dimension(810, 560));
        content.setLayout(new java.awt.BorderLayout());

        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });

        logosP.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>\n<div style='text-align: center;'>\nINSTITUTO FEDERAL DE DEFENSORIA PUBLICA <br>\nDELEGACIÓN BAJA CALIFORNIA SUR \n</div>\n</html>");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout logosPLayout = new javax.swing.GroupLayout(logosP);
        logosP.setLayout(logosPLayout);
        logosPLayout.setHorizontalGroup(
            logosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logosPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo1L, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logo2L, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        logosPLayout.setVerticalGroup(
            logosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logosPLayout.createSequentialGroup()
                .addGroup(logosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logosPLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(logosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo2L, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logo1L, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(logosPLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(logosP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(91, 91, 91))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logosP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 534, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("frame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirm = JOptionPane.showOptionDialog(null, "¿Cerrar la aplicación?","Confirmación de salida",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (confirm == 0){
                HibernateUtil.shutdown();
                System.exit(0);
            }
    }//GEN-LAST:event_formWindowClosing

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        usuarioActual = usuario.getSelectedItem().toString().toUpperCase();
        if (usuarioActual.equals("DELEGADO")){
            int res = JOptionPane.showConfirmDialog(null, contrasPanel, "Verificación", JOptionPane.OK_CANCEL_OPTION);
            String contra = new String(contraF.getPassword());
            contraF.setText("");
            if (res == JOptionPane.OK_OPTION && contra.equals(delPass)){
                ArrayList<String> viewAdds = new ArrayList();
                viewAdds.add("TODOS");
                cambiarContent(vistaSalidas);
                initDefs(vistaSalidas.getBuscador(), viewAdds);
                vistaSalidas.initTable();
                volver.setVisible(true);
            } else if (res == JOptionPane.OK_OPTION){
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
        } else if (usuarioActual.equals("ADMIN")){
            int res = JOptionPane.showConfirmDialog(null, contrasPanel, "Verificación", JOptionPane.OK_CANCEL_OPTION);
            String contra = new String(contraF.getPassword());
            contraF.setText("");
            if (res == JOptionPane.OK_OPTION && contra.equals(adminPass)){
                cambiarContent(editor);
                initDefs(editor.getDefsEdit(), null);
                volver.setVisible(true);
            } else if (res == JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
            }
        } else {
            vistaAdd = new addPanel(usuarioActual);
            cambiarContent(vistaAdd);
            volver.setVisible(true);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        cambiarContent(loginPanel);
        initDefs(usuario, loginAdds);
        setPass();
        volver.setVisible(false);
    }//GEN-LAST:event_volverMouseClicked

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setBackground(new Color(234, 234, 234));
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_volverMouseExited

    private void mostrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCActionPerformed
        if (mostrarC.isSelected()) {
            contraF.setEchoChar((char) 0);
            mostrarC.setText("Ocultar");
        } else {
            contraF.setEchoChar('•');
            mostrarC.setText("Mostrar");
        }
    }//GEN-LAST:event_mostrarCActionPerformed

    private void dbContraTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbContraTActionPerformed
        togglePass(dbContra, dbContraT);
    }//GEN-LAST:event_dbContraTActionPerformed

    public void cambiarContent(JPanel p){
        SwingUtilities.invokeLater(() -> {
            p.setPreferredSize(new Dimension(content.getWidth(), content.getHeight()));
            p.setLocation(0, 0);
            content.removeAll();
            content.add(p, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
        });
    }
    
    public static void initDefs(JComboBox cb, ArrayList<String> adds){
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            cb.removeAllItems();
            if (adds != null){
                for (String s:adds){
                    cb.addItem(s);
                }
            }
            if (session.isConnected()){
                List<Defensor> defs = session.createQuery("from Defensor d order by d.nombre asc", Defensor.class).list();
                for (Defensor d: defs){
                    cb.addItem(d.getNombre());
                }
            }
        } catch (Exception e) {
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
            e.printStackTrace();
        } finally {
            session.close();
        }
    }
    
    private ImageIcon resizeImage(Image image, JLabel label){
        ImageIcon img = new ImageIcon(image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH));
        return img;
    }
    
    public static void exportTable(JTable t){
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar como");

        // Filtrar para mostrar solo archivos .xlsx
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos Excel (*.xlsx)", "xlsx"));
        
        Frame[] f = gui.getFrames();
        int userSelection = fileChooser.showSaveDialog(f[0]);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            // Añadir la extensión .xlsx si no está presente
            if (!fileToSave.getAbsolutePath().endsWith(".xlsx")) {
                fileToSave = new File(fileToSave + ".xlsx");
            }

            ExcelExporter exporter = new ExcelExporter();
            try {
                exporter.exportTable(t, fileToSave.getAbsolutePath());
                JOptionPane.showMessageDialog(null, "Archivo guardado satisfacoriamente en: "+fileToSave.getAbsolutePath());
            } catch (IOException ex) {
                 ex.printStackTrace();
            }
        }
    }
    
    private ImageIcon getImg(String n){
        ClassLoader classLoader = getClass().getClassLoader();
        java.net.URL iconURL = classLoader.getResource(n+".png");
        if (iconURL != null) {
            return new ImageIcon(iconURL);
        } else {
            System.err.println("No se pudo encontrar el icono");
            return new ImageIcon("src/main/resources/img/"+n+".png");
        }
    }
    
    public static void togglePass(JPasswordField p, JToggleButton b){
        if (b.isSelected()) {
            p.setEchoChar((char) 0);
            b.setText("Ocultar");
        } else {
            p.setEchoChar('•');
            b.setText("Mostrar");
        }
    }
    
    private void connect(){
        //Connects to the database
        File props = new File("C://salidas-hibernate/hibernate.cfg.xml");
        if (!props.exists()){
            try {
                props.createNewFile();
                int res = JOptionPane.showConfirmDialog(null, dbConfigP, "Configuración de Base de Datos", JOptionPane.OK_CANCEL_OPTION);
                if (res == JOptionPane.OK_OPTION && !urlTF.getText().isBlank() && !usuarioTF.getText().isBlank() && dbContra.getPassword().length != 0){
                    String url = urlTF.getText();
                    String user = usuarioTF.getText();
                    String pass = new String(dbContra.getPassword());
                    String write = HibernateUtil.generateConfigContent(url, user, pass);
                    HibernateUtil.writeFile(props.getAbsolutePath(), write);
                } else {
                    JOptionPane.showMessageDialog(null, "Presente todos los datos necesaios. La conexión a la base de datos es necesaria.");
                    props.delete();
                    System.exit(0);
                }
            } catch(IOException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        HibernateUtil.newConnection();
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    
    
    public static void main(String args[]) {
        FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel content;
    private javax.swing.JPasswordField contraF;
    private javax.swing.JPanel contrasPanel;
    private javax.swing.JPanel dbConfigP;
    private javax.swing.JPasswordField dbContra;
    private javax.swing.JToggleButton dbContraT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logo1L;
    private javax.swing.JLabel logo2L;
    private javax.swing.JPanel logosP;
    private javax.swing.JToggleButton mostrarC;
    private javax.swing.JTextField urlTF;
    private javax.swing.JComboBox<String> usuario;
    private javax.swing.JTextField usuarioTF;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
