/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.controlsalidas;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author Keloc
 */
public class viewPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewPanel
     */
    public viewPanel() {
        initComponents();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtros = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscador = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        semanaBtn = new javax.swing.JRadioButton();
        mesBtn = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSalidas = new javax.swing.JTable();
        todoBtn = new javax.swing.JRadioButton();

        setMinimumSize(new java.awt.Dimension(720, 465));
        setPreferredSize(new java.awt.Dimension(720, 465));

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SALIDAS");

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        filtros.add(semanaBtn);
        semanaBtn.setForeground(new java.awt.Color(0, 0, 0));
        semanaBtn.setText("Esta Semana");
        semanaBtn.setActionCommand("SEMANA");
        semanaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semanaBtnActionPerformed(evt);
            }
        });

        filtros.add(mesBtn);
        mesBtn.setForeground(new java.awt.Color(0, 0, 0));
        mesBtn.setText("Este Mes");
        mesBtn.setActionCommand("MES");
        mesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesBtnActionPerformed(evt);
            }
        });

        tablaSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CONS.", "DEFENSOR", "FECHA", "HORA SALIDA", "TIPO DE DILIGENCIA", "LUGAR", "EXP. DE CONTROL", "TIEMPO APROX. DE DURACION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaSalidas);

        filtros.add(todoBtn);
        todoBtn.setForeground(new java.awt.Color(0, 0, 0));
        todoBtn.setSelected(true);
        todoBtn.setText("Todo");
        todoBtn.setActionCommand("TODO");
        todoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(633, 633, 633))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(todoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mesBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semanaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBtn)
                    .addComponent(mesBtn)
                    .addComponent(semanaBtn)
                    .addComponent(todoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(191, 191, 191))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesBtnActionPerformed
        initTable();
    }//GEN-LAST:event_mesBtnActionPerformed

    private void semanaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semanaBtnActionPerformed
        initTable();
    }//GEN-LAST:event_semanaBtnActionPerformed

    private void todoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todoBtnActionPerformed
        initTable();
    }//GEN-LAST:event_todoBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        initTable();
    }//GEN-LAST:event_buscarBtnActionPerformed


    public void initTable(){
        Session session = HibernateUtil.getSessionFactory().openSession();
        LocalDate d = LocalDate.now();
        LocalDate inicio;
        List<Salida> salidas;
        try{
            session.beginTransaction();
            //filtrar
            if (filtros.getSelection().getActionCommand().equals("MES")){
                inicio = d.minusDays(d.getDayOfMonth()-1);
                salidas = filtrar(inicio, d, buscador.getText().toUpperCase(), session);
            } else if(filtros.getSelection().getActionCommand().equals("SEMANA")){
                inicio = d.minusDays(d.getDayOfWeek().getValue()-1);
                salidas = filtrar(inicio, d, buscador.getText().toUpperCase(), session);
            } else {
                inicio = (LocalDate) session.createQuery("select min(s.fecha) from Salida s").uniqueResult();
                salidas = filtrar(inicio, d, buscador.getText().toUpperCase(), session);
            }
            setTable(salidas);
            session.getTransaction().commit();
            session.close();
        } catch(Exception e){
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
            e.printStackTrace();
        } finally {
                session.close();
        }
    }
    private List<Salida> filtrar(LocalDate inicio, LocalDate hoy, String buscador, Session session){
        List<Salida> filtrada;
        if (buscador.isBlank()){
            filtrada = session.createQuery("From Salida where fecha between :fInicio and :fActual", Salida.class)
                .setParameter("fInicio", inicio)
                .setParameter("fActual", hoy)
                .getResultList();
        } else {
            filtrada = session.createQuery("select s from Salida s join s.defensor d where s.fecha between :fInicio and :fActual and"+
                "(upper(d.nombre) like :b or upper(s.diligencia) like :b or upper(s.expediente) like :b or upper(s.lugar) like :b)", Salida.class)
                .setParameter("fInicio", inicio)
                .setParameter("fActual", hoy)
                .setParameter("b", "%"+buscador+"%")
                .getResultList();
        }
        return filtrada;
    }
    private void setTable(List<Salida> l){
        String[] tblH = {"CONS.","DEFENSOR","FECHA","HORA SALIDA","TIPO DE DILIGENCIA","LUGAR","EXPEDIENTE DE CONTROL","TIEMPO APROX. DE DURACIÓN"};
        DefaultTableModel model = new DefaultTableModel(tblH, 0);
        int i = 1;
        for(Salida s:l){
            Object[] row = {i, s.getDefId().getNombre().toUpperCase(), s.getFecha(), s.getHora(), s.getDiligencia().toUpperCase(), s.getLugar().toUpperCase(), s.getExpediente().toUpperCase(), s.getDuracion().toUpperCase()};
            model.addRow(row);
            i++;
        }
        tablaSalidas.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JTextField buscador;
    private javax.swing.JButton buscarBtn;
    private javax.swing.ButtonGroup filtros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton mesBtn;
    private javax.swing.JRadioButton semanaBtn;
    private javax.swing.JTable tablaSalidas;
    private javax.swing.JRadioButton todoBtn;
    // End of variables declaration//GEN-END:variables
}
